# Generated by Django 3.0.5 on 2020-04-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Value')),
                ('qty', models.IntegerField(verbose_name='Quantity')),
            ],
        ),
    ]
